services:
  - type: web
    name: sistema-gestion-backend
    env: node
    buildCommand: npm install
    startCommand: npm run start:prod
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        sync: false
      - key: PORT
        sync: false